---
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pest consumption by generalist arthropod predators increases with crop stage in both organic and conventional farms

Hsu, G.-C., J.-A. Ou, and C.-K. Ho. 2021. Pest consumption by generalist arthropod predators increases withcrop stage in both organic and conventional farms. _Ecosphere_ 12:e03625. 

## Abstract
Biocontrol agents are critical for pest management in sustainable agriculture. Generalist arthropod predators may hold a great potential as biocontrol agents because they are ubiquitous and consume pests in agroecosystems. However, their diet composition over the entire crop season has rarely been quantified, which hinders our ability to assess their biocontrol potential in real field conditions that foster temporal dynamics of pest and alternative prey populations. To fill this knowledge gap, we surveyed arthropod communities over crop stages in organic and conventional rice farms (n = 7 each) and used stable isotope analysis (δ^13^C and δ^15^N) to quantify the diet composition of generalist arthropod predators over time. We aimed to (1) examine the resource partitioning (trophic niches) in these predators, (2) quantify these predators’ diet composition from potential prey sources (rice herbivores, tourist herbivores, and detritivores), and (3) investigate the effects of farm type (organic/conventional) and crop stage (tillering/flowering/ripening stage) on pest (rice herbivore) consumption by the predators. The results show that generalist predators in both organic and conventional farms shifted trophic niches over the crop season and consumed a higher percentage of rice herbivores at late than at early crop stages (e.g., 90–93% at ripening vs. 34–55% at tillering), suggesting an increasing biocontrol value over time regardless of farm type. Surprisingly, generalist predators consumed higher proportions of rice herbivores in conventional than organic farms at tillering and flowering stages, highlighting their underappreciated potential as biocontrol agents in conventional farms. These results demonstrate that although generalist arthropod predators do consume non-pest alternative prey, they have a high biocontrol potential (per capita pest consumption) in both organic and conventional rice farms. We encourage modern agriculture to develop techniques to support robust populations of these predators and the ecosystem services that they provide.

## Article link
[https://doi.org/10.1002/ecs2.3625](https://doi.org/10.1002/ecs2.3625)






